### ISSUE TITLE
Running Phamb on long reads polished with short reads

### ISSUE THREAD

**Issue by emilyjunkins** [RasmussenLab/phamb#29]
Hello,

I have long read nanopore data assembled with flye and polished with illumina reads. Is phamb compatible with a long read assembler like flye?

**Comment by joacjo** [comment]
Hi Emily 

Yes Phamb is compatible, I am assuming at this point you are binning the long-read assembled contigs. Even though we have not benchmarked this, I would think that long-read assembled contigs should improve both Viral-binning and prediction of viral bins.
If you have no intention of running binning on your contigs to improve viral completeness and rescue viral fragmentation, I would short-cut to running CheckV or Vibrant on the long-read contigs.

Best,
Joachim
