### ISSUE TITLE
Running Phamb without reads

### ISSUE THREAD

**Issue by jjensen44** [RasmussenLab/phamb#36]
Hi! Is it possible to run PHAMB on a set of contigs that lack any contributing short reads (eg just a fasta of viral contigs). From the documentation this doesn't seem possible since VAMB requires the coabundance/coverage information upstream of PHAMB- but if so would be interested in how to run correctly- thanks!

**Comment by joacjo** [comment]
Hi jjensen44 

If you have a set of viral contigs i.e. from a metavirome sample and do not intend to run VAMB anyway, you can run a viral evaluator like CheckV on those directly. That would be my advice. 

Good luck!  

Best,
Joachim
