### ISSUE TITLE
Versioned release package for Phamb

### ISSUE THREAD

**Issue by jayramr** [RasmussenLab/phamb#42]
I'm working  to make Phamb available on Bioconda. 

Please refer. -> https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release

I need your help creating a versioned release to use for the Bioconda recipe. Once Phamb is added to Bioconda, it'll also be made available as a Docker container from Biocontainers, and as a Singularity image from the Galaxy Project. The Bioconda bot will also recognize future releases and automatically update the recipe.

Please let me know 

Thanks
Jay

**Comment by jayramr** [comment]
Any update on this?

**Comment by jayramr** [comment]
Dear @simonrasmu 


I would request you to release the versioning for this package as per 
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release

Please advise 

Thanks
Jay

**Comment by simonrasmu** [comment]
@joacjo @jakobnissen

**Comment by joacjo** [comment]
Dear @jayramr  - Kudos to your efforts on making Phamb available on Bioconda!
Apologize for our delayed response to this issue. 

A versioned release is now available. Thank you!
Let us know if there are anything we can do. 

Best,
Joachim

**Comment by jayramr** [comment]
Thank you so much

**Comment by jayramr** [comment]
Dear @joacjo 

I'm facing some issue with building this package in bioconda.
As per the community recommendation, could you convert the same into a python package?

So i can easily push/merge this as a bioconda package

Please advise

**Comment by joacjo** [comment]
Hi Jay 

I created a python package on the `dev` branch, can you check if that solves your issue with creating the bioconda package? Also let me know if you face any issues with the installation. 
It would be great to know if this solves the issue before I push it to master. 

Best,
Joachim

**Comment by jayramr** [comment]
Sure thanks, let me try to test this today and update you

**Comment by jayramr** [comment]
@joacjo i tried to test this dev version.
Here is my testing flow
-> Create a conda env with python 3.9
-> python setup.py install ( no errors found ) 
{code}
(phamb) jr5241@DCLAP-V1342-CGSB:/data/install/jaya/phamb$ python setup.py install
running install
/data/miniconda3/envs/phamb/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/data/miniconda3/envs/phamb/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
creating phamb.egg-info
writing phamb.egg-info/PKG-INFO
writing dependency_links to phamb.egg-info/dependency_links.txt
writing top-level names to phamb.egg-info/top_level.txt
writing manifest file 'phamb.egg-info/SOURCES.txt'
reading manifest file 'phamb.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'phamb.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/phamb
copying phamb/vambtools.py -> build/lib/phamb
copying phamb/split_contigs.py -> build/lib/phamb
copying phamb/run_RF_modules.py -> build/lib/phamb
copying phamb/run_RF.py -> build/lib/phamb
copying phamb/__init__.py -> build/lib/phamb
creating build/lib/phamb/dbs
copying phamb/dbs/RF_model.python39.sav -> build/lib/phamb/dbs
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/phamb
creating build/bdist.linux-x86_64/egg/phamb/dbs
copying build/lib/phamb/dbs/RF_model.python39.sav -> build/bdist.linux-x86_64/egg/phamb/dbs
copying build/lib/phamb/vambtools.py -> build/bdist.linux-x86_64/egg/phamb
copying build/lib/phamb/split_contigs.py -> build/bdist.linux-x86_64/egg/phamb
copying build/lib/phamb/run_RF_modules.py -> build/bdist.linux-x86_64/egg/phamb
copying build/lib/phamb/run_RF.py -> build/bdist.linux-x86_64/egg/phamb
copying build/lib/phamb/__init__.py -> build/bdist.linux-x86_64/egg/phamb
byte-compiling build/bdist.linux-x86_64/egg/phamb/vambtools.py to vambtools.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/phamb/split_contigs.py to split_contigs.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/phamb/run_RF_modules.py to run_RF_modules.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/phamb/run_RF.py to run_RF.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/phamb/__init__.py to __init__.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-3.7
copying and adjusting phamb/run_RF.py -> build/scripts-3.7
copying and adjusting phamb/split_contigs.py -> build/scripts-3.7
copying phamb/vambtools.py -> build/scripts-3.7
copying and adjusting phamb/run_RF_modules.py -> build/scripts-3.7
changing mode of build/scripts-3.7/run_RF.py from 664 to 775
changing mode of build/scripts-3.7/split_contigs.py from 664 to 775
changing mode of build/scripts-3.7/run_RF_modules.py from 664 to 775
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.7/vambtools.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.7/split_contigs.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.7/run_RF_modules.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.7/run_RF.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/vambtools.py to 775
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/split_contigs.py to 775
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/run_RF_modules.py to 775
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/run_RF.py to 775
copying phamb.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying phamb.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying phamb.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying phamb.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
phamb.__pycache__.run_RF.cpython-37: module references __file__
creating dist
creating 'dist/phamb-1.0.1-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing phamb-1.0.1-py3.7.egg
creating /data/miniconda3/envs/phamb/lib/python3.7/site-packages/phamb-1.0.1-py3.7.egg
Extracting phamb-1.0.1-py3.7.egg to /data/miniconda3/envs/phamb/lib/python3.7/site-packages
Adding phamb 1.0.1 to easy-install.pth file
Installing vambtools.py script to /data/miniconda3/envs/phamb/bin
Installing split_contigs.py script to /data/miniconda3/envs/phamb/bin
Installing run_RF_modules.py script to /data/miniconda3/envs/phamb/bin
Installing run_RF.py script to /data/miniconda3/envs/phamb/bin

Installed /data/miniconda3/envs/phamb/lib/python3.7/site-packages/phamb-1.0.1-py3.7.egg
Processing dependencies for phamb==1.0.1
Finished processing dependencies for phamb==1.0.1
{code}

Then I tested the phamb using below command. but i got error as numpy, sklearn missing
-> run_RF.py 

I have two questions

1) What are prerequsites for installing phamb?
2) Once this is installed how to test whether this module/application is working ? 

Thanks
Jay

**Comment by joacjo** [comment]
Hi Jay 

I specified the following the dependency for scikit learn `mamba install -c conda-forge -c bioconda scikit-learn=1.0.2` 
I can try to package the programme with this dependency, such that it is installed automatically by pip. 

Best,
Joachim

**Comment by jayramr** [comment]
Hi @joacjo yes please pls package them, i will test.

Also please advise for below point 
"Once this is installed how to test whether this module/application is working ?"

**Comment by joacjo** [comment]
Hi Jay 

Check out the updated dev branch. You can test the installation by 

```
pip install -e .

### Test installation
mkdir -p testout 
run_RF.py test/contigs.fna.gz test/clusters.tsv test testout
```

**Comment by jayramr** [comment]
Thanks this worked well :) please push this as official version one

**Comment by joacjo** [comment]
Great! 

Note the new tag: v.1.0.1. 

Best,
Joachim

**Comment by jayramr** [comment]
Hi @joacjo phamb is integrated to bioconda. 

https://anaconda.org/bioconda/phamb 

Please close this tracker

**Comment by joacjo** [comment]
Great. I will update the README with instructions for now Bioconda based installation.
