### ISSUE TITLE
contig length

### ISSUE THREAD

**Issue by Dorothydu12** [RasmussenLab/phamb#45]
Hi,

If I use contig with more than 1000 lengths, the only I need to do is change the parameter in RF.py and RF_modules.py, right?

Thanks!

**Comment by joacjo** [comment]
Hi Dorothy
I assume that you also ran VAMB including contigs with >1000 bp in length?
In that case, yes you can simply change the contig filtering parameter in the RF-scripts. 

Best,
Joachim
