### ISSUE TITLE
split_contigs.py produces empty files

### ISSUE THREAD

**Issue by Sanrrone** [RasmussenLab/phamb#48]
Dears,
I am trying to run phamb (cloned repo) in parallel and when I used split_contigs.py as the code below
```
python split_contigs.py -c contigs.fna.gz
```
it is produces and empty ´assembly´ folder and an empty ´sample_table.txt´ file. I tried with an gunziped contig file and is the same result.
What should I do?

thanks in advance!,
Sandro

**Comment by joacjo** [comment]
Hi Sandro

Apologise for the late response.

It sounds like your contigs are not named in a way that works with the script. Can you show me an example of your contig headers?

Best,
Joachim
