### ISSUE TITLE
Can PHAMB output comparable performance on environmental metagenome compared to gut metagenome

### ISSUE THREAD

**Issue by liangjinsong** [RasmussenLab/phamb#49]
Hi, given the Random Forest (RF) model to distinguish viral-like from bacterial-like genome bins in PHAMB was based on gut metagenome, I am wondering that can phamb output comparable performance on environmental metagenome compared to non-gut metagenome? Have you tested the performance of PHAMB on environmental metagenome?

Thank you in advance!

**Comment by joacjo** [comment]
Hi Liang 

Unfortunately, we have not benchmarked Phamb performance on environmental metagenomes.

Best,
Joachim
