### ISSUE TITLE
split_contigs.py produces empty files

### ISSUE THREAD

**Issue by ChaoXianSen** [RasmussenLab/phamb#50]
HI,
I am trying to run phamb in parallel-annotation mode, and when I used split_contigs.py as the code below
python split_contigs.py -c contigs.fna.gz
the results ´assembly´ folder and ´sample_table.txt´ file are empty. 
What should I do?

thanks !

**Comment by joacjo** [comment]
Hi Chao 

It sounds like your contigs are not named in a way that works with the script.
Contigs named i.e. like this would work with the default split (-s "C") parameter of the script
>Sample1Contig1 
>Sample1Contig2
Show me an example of your contig headers, then it's easier to figure out.

**Comment by ChaoXianSen** [comment]
> Hi Chao
> 
> It sounds like your contigs are not named in a way that works with the script. Contigs named i.e. like this would work with the default split (-s "C") parameter of the script
> 
> > Sample1Contig1
> > Sample1Contig2
> > Show me an example of your contig headers, then it's easier to figure out.

thanks a lot, i have solved this question~
