### ISSUE TITLE
What are the criteria of RF model

### ISSUE THREAD

**Issue by ChaoXianSen** [RasmussenLab/phamb#52]
Hi ！
 What score, or threshold of RF model is used to classify bacteria from viruses?

thanks!

**Comment by joacjo** [comment]
Hi Chao 

The RF model has been trained as described in the paper - by default the code do not filter on an arbritary cutoff or threshold but utilise the label-prediction of the model.

Best,
Joachim

**Comment by enryH** [comment]
But this then probably means that 50 percent of the trees need to predict the contig as virus?
