### ISSUE TITLE
VAE or AAE?

### ISSUE THREAD

**Issue by yqy6611** [RasmussenLab/phamb#57]
Hi all,
I'd like to learn which cluster file generated by vamb is suitable for feeding to phamb, that via VAE or AAE. Many thanks!

**Comment by joacjo** [comment]
Hi Qiyi Yuan 

We have only benchmarked using the clusters from the VAE model to phamb, so I would advise to you that one. 
However, you can make your own small benchmark to learn if there is a benefit to use the AAE derived clusters on your data by evaluating the number of HQ vMAGs you achieve from using either one.
